### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by ahaynssen** [vibrato/aws-snapshot#1]
I'd love to use your cleanup script in a lambda, but wanted to clarify what sort of licensing you're using for this project. Thanks!

**Comment by jamielennox** [comment]
Hey, thanks for pointing this out. We definitely want a license on all our public repos.

I haven't worked on this code but it appears the pl_mongo folder is a fork from https://github.com/Percona-Lab/mongodb_consistent_backup which is under Apache2, so it makes sense to follow that here. 

We hope it's helpful.
